apiVersion: v1
kind: Pod
metadata:
  name: conv-app
  labels:
    components: convapp
spec:
  containers:
    - name: short-app
      image: antonlarichev/conv-app:1.2
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
